# Generated by Django 2.1.15 on 2020-10-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='full name')),
                ('abstract', models.CharField(max_length=100, verbose_name='full name')),
                ('authors', models.CharField(max_length=100, verbose_name='full name')),
                ('keywords', models.CharField(max_length=100, verbose_name='full name')),
                ('affiliation', models.CharField(max_length=100, verbose_name='full name')),
                ('month', models.CharField(max_length=100, verbose_name='full name')),
                ('link', models.CharField(max_length=100, verbose_name='full name')),
                ('journal_name', models.CharField(max_length=100, verbose_name='full name')),
                ('year', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
